//! Application configuration: file, environment, defaults.
//!
//! Values are resolved in precedence order **environment > `config.toml` > default**: a
//! `LOOK_ABOVE_*` variable beats the file, which beats the built-in default. `OpenSky`
//! credentials have one extra rung below the file — see [`DEFAULT_CREDENTIALS_PATH`].
//!
//! Two failure modes are deliberately different (see `plans/DECISION_LOG.md`, 2026-07-15):
//! an **absent** `config.toml` is normal and yields defaults, while one that is **present
//! but unreadable or unparseable** is a hard error. A broken file means the operator meant
//! to configure something; defaulting silently would hide the typo.
//!
//! Credential values never appear in `Debug` output (privacy rule 7.1) — see
//! [`SecretString`].

use std::env::VarError;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};
use look_above_ingest::opensky::Credentials;
use serde::Deserialize;

/// Credential material with a redacted `Debug`.
///
/// Re-exported from `core` because `ingest` holds credentials too (it sends them), and
/// privacy rule 7.1 implemented in two places is privacy rule 7.1 enforced in one.
pub use look_above_core::secret::SecretString;

/// Where [`Config::load_default`] looks, relative to the working directory.
pub const DEFAULT_CONFIG_PATH: &str = "config.toml";

/// Where [`Config::load_default`] looks for `OpenSky`'s downloaded credentials file.
///
/// `OpenSky`'s account page hands out an API client as a `credentials.json`
/// (`{"clientId": "...", "clientSecret": "..."}`), and reading that file as-is removes the
/// copy-paste step between their download and our config — the step where a character goes
/// missing, or where a secret lands in a file that is not gitignored.
///
/// It sits *below* `config.toml` in precedence and is consulted only when neither half of
/// the credential was configured anywhere else; see [`Config::apply_credentials_file`].
pub const DEFAULT_CREDENTIALS_PATH: &str = "credentials.json";

const ENV_LOG_FILTER: &str = "LOOK_ABOVE_LOG_FILTER";
const ENV_OPENSKY_CLIENT_ID: &str = "LOOK_ABOVE_OPENSKY_CLIENT_ID";
const ENV_OPENSKY_CLIENT_SECRET: &str = "LOOK_ABOVE_OPENSKY_CLIENT_SECRET";
const ENV_DB_PATH: &str = "LOOK_ABOVE_DB_PATH";
const ENV_RETENTION_HOURS: &str = "LOOK_ABOVE_RETENTION_HOURS";

/// Our crates at info, the rest of the world at warn.
const DEFAULT_LOG_FILTER: &str = "look_above=info,warn";

const DEFAULT_DB_PATH: &str = "look_above.db";

/// Privacy rule 5.1: position history defaults to 24 h…
pub const RETENTION_HOURS_DEFAULT: u32 = 24;

/// …and may never exceed 7 days.
pub const RETENTION_HOURS_MAX: u32 = 24 * 7;

/// A read-only view of the process environment.
///
/// Injected rather than read directly so tests never touch the real environment:
/// `std::env::set_var` is `unsafe` in edition 2024, and the environment is process-global
/// state that parallel tests would race on.
pub trait EnvSource {
    /// The value of `key`.
    ///
    /// `Ok(None)` means the variable is unset. An `Err` means it is *present but unusable* —
    /// a different case, which must not quietly read as absent.
    fn var(&self, key: &str) -> Result<Option<String>>;
}

/// The real process environment.
#[derive(Debug, Clone, Copy)]
pub struct SystemEnv;

impl EnvSource for SystemEnv {
    fn var(&self, key: &str) -> Result<Option<String>> {
        match std::env::var(key) {
            Ok(value) => Ok(Some(value)),
            Err(VarError::NotPresent) => Ok(None),
            // `std::env::var` reports "unset" and "set to something that is not valid
            // Unicode" as the same `Err` type, and `.ok()` would flatten both to `None` —
            // turning a broken credential into an absent one. On Windows the environment is
            // UTF-16, so this is reachable, not theoretical. The message never echoes the
            // value: it may be the secret itself (privacy rule 7.1).
            Err(VarError::NotUnicode(_)) => Err(anyhow!(
                "{key} is set but is not valid Unicode, so it cannot be read as a \
                 configuration value; unset it or set it to a valid value"
            )),
        }
    }
}

/// `OpenSky`'s `credentials.json`, exactly as their account page hands it out.
///
/// Unknown fields are **allowed** here, unlike in [`Config`]. The asymmetry is deliberate:
/// `config.toml` is written by a human, so an unknown key is a typo that would silently
/// read as "absent" — whereas this file is generated by `OpenSky`, so an unknown key is
/// `OpenSky` adding a field, and refusing to start over it would be us breaking on their
/// release note.
#[derive(Debug, Clone, Deserialize)]
struct CredentialsFile {
    #[serde(rename = "clientId")]
    client_id: SecretString,
    #[serde(rename = "clientSecret")]
    client_secret: SecretString,
}

/// The whole of the application's configuration.
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Config {
    pub log: LogConfig,
    pub sources: SourcesConfig,
    pub storage: StorageConfig,

    /// The file this was read from, or `None` when no file existed and defaults were used.
    /// Not a config key — [`Config::load`] fills it in.
    #[serde(skip)]
    pub source_path: Option<PathBuf>,

    /// The credentials file the `OpenSky` credential came from, when it came from one.
    /// Not a config key — [`Config::load`] fills it in.
    #[serde(skip)]
    pub credentials_path: Option<PathBuf>,
}

/// Logging.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct LogConfig {
    /// A `tracing-subscriber` `EnvFilter` directive string, e.g. `look_above=debug,warn`.
    pub filter: String,
}

impl Default for LogConfig {
    fn default() -> Self {
        Self {
            filter: DEFAULT_LOG_FILTER.to_owned(),
        }
    }
}

/// Live data sources.
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct SourcesConfig {
    pub opensky: OpenSkyConfig,
}

/// `OpenSky` `OAuth2` client-credentials.
///
/// Both are absent until the owner creates a free API client (M1 item 1.3); the no-key
/// community fallbacks need no credentials at all.
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct OpenSkyConfig {
    pub client_id: Option<SecretString>,
    pub client_secret: Option<SecretString>,
}

impl OpenSkyConfig {
    /// Whether both halves of the credential are present.
    ///
    /// [`Config::load`] rejects half a pair, so this answers "can we authenticate?".
    pub fn is_configured(&self) -> bool {
        self.client_id.is_some() && self.client_secret.is_some()
    }

    /// The credential in the shape `ingest` takes, or `None` when `OpenSky` is unconfigured.
    ///
    /// `None` is the disabled source, not a failure:
    /// [`OpenSkyAuth::from_optional`](look_above_ingest::opensky::OpenSkyAuth::from_optional)
    /// is the other side of this seam — `headless::run` (item 1.12) is the caller.
    pub fn credentials(&self) -> Option<Credentials> {
        match (&self.client_id, &self.client_secret) {
            (Some(client_id), Some(client_secret)) => {
                Some(Credentials::new(client_id.clone(), client_secret.clone()))
            }
            _ => None,
        }
    }
}

/// Local persistence.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct StorageConfig {
    /// The `SQLite` database file, relative to the working directory unless absolute.
    pub db_path: PathBuf,

    /// How long position history is kept, in hours.
    ///
    /// Privacy rule 5.1: default 24 h, hard maximum 7 days, configurable downward only.
    pub retention_hours: u32,
}

impl Default for StorageConfig {
    fn default() -> Self {
        Self {
            db_path: PathBuf::from(DEFAULT_DB_PATH),
            retention_hours: RETENTION_HOURS_DEFAULT,
        }
    }
}

impl Config {
    /// Load from [`DEFAULT_CONFIG_PATH`] and [`DEFAULT_CREDENTIALS_PATH`] in the working
    /// directory, with environment overrides applied on top.
    pub fn load_default(env: &impl EnvSource) -> Result<Self> {
        Self::load(Path::new(DEFAULT_CONFIG_PATH), env)
    }

    /// Load from `path` and the default credentials file, then apply `LOOK_ABOVE_*`
    /// overrides from `env`.
    pub fn load(path: &Path, env: &impl EnvSource) -> Result<Self> {
        Self::load_from(path, Path::new(DEFAULT_CREDENTIALS_PATH), env)
    }

    /// Load from explicit paths — [`load`](Self::load) with the credentials file named.
    ///
    /// A missing `path` is not an error: it yields defaults, plus any environment
    /// overrides. Every other read failure, and any file that does not parse, is an error.
    pub fn load_from(path: &Path, credentials_path: &Path, env: &impl EnvSource) -> Result<Self> {
        let mut config = match std::fs::read_to_string(path) {
            Ok(text) => {
                let mut parsed: Self = toml::from_str(&text)
                    .with_context(|| format!("{} is not valid configuration", path.display()))?;
                parsed.source_path = Some(path.to_path_buf());
                parsed
            }
            Err(err) if err.kind() == ErrorKind::NotFound => Self::default(),
            Err(err) => {
                return Err(err).with_context(|| format!("cannot read {}", path.display()));
            }
        };

        config.apply_env(env)?;
        // Before `normalize`, a blank `client_id = ""` from config.example.toml is still
        // `Some("")`. Normalizing first is what lets an untouched example file fall through
        // to the credentials file rather than reading as "the operator chose blank".
        config.normalize();
        config.apply_credentials_file(credentials_path)?;
        config.validate()?;
        Ok(config)
    }

    /// Overlay `LOOK_ABOVE_*` variables. Present-but-unparseable values are errors, for the
    /// same reason a broken file is.
    fn apply_env(&mut self, env: &impl EnvSource) -> Result<()> {
        if let Some(value) = env.var(ENV_LOG_FILTER)? {
            self.log.filter = value;
        }
        if let Some(value) = env.var(ENV_OPENSKY_CLIENT_ID)? {
            self.sources.opensky.client_id = Some(SecretString::from(value));
        }
        if let Some(value) = env.var(ENV_OPENSKY_CLIENT_SECRET)? {
            self.sources.opensky.client_secret = Some(SecretString::from(value));
        }
        if let Some(value) = env.var(ENV_DB_PATH)? {
            self.storage.db_path = PathBuf::from(value);
        }
        if let Some(value) = env.var(ENV_RETENTION_HOURS)? {
            self.storage.retention_hours = value.trim().parse().with_context(|| {
                format!("{ENV_RETENTION_HOURS} must be a whole number of hours, got {value:?}")
            })?;
        }
        Ok(())
    }

    /// A blank credential means "absent", so that `config.example.toml` behaves like no
    /// file when copied verbatim, and an empty `LOOK_ABOVE_OPENSKY_CLIENT_ID=` does not
    /// masquerade as a credential.
    fn normalize(&mut self) {
        let opensky = &mut self.sources.opensky;
        opensky.client_id = opensky.client_id.take().filter(|secret| !secret.is_blank());
        opensky.client_secret = opensky
            .client_secret
            .take()
            .filter(|secret| !secret.is_blank());
    }

    /// Fill the `OpenSky` credential from `OpenSky`'s own `credentials.json`, if nothing
    /// else supplied one.
    ///
    /// **All or nothing.** If the environment or `config.toml` named *either* half, this
    /// file is not consulted at all. The two values are one credential issued as a pair, so
    /// completing a config.toml `client_id` with a `clientSecret` from here would build a
    /// mismatched pair that authenticates as nobody — a 401 whose cause is invisible from
    /// either file. (Env-completes-file is still supported for the `config.toml` path, where
    /// the halves are entered by hand and splitting them across a shared machine is the
    /// documented reason to.)
    ///
    /// **Absent is fine; broken is not** — the same rule `config.toml` follows. A file that
    /// exists means the operator meant to authenticate, so a parse failure is louder than
    /// quietly dropping to the no-key fallbacks and wondering later why the credits never
    /// moved.
    fn apply_credentials_file(&mut self, path: &Path) -> Result<()> {
        let opensky = &self.sources.opensky;
        if opensky.client_id.is_some() || opensky.client_secret.is_some() {
            return Ok(());
        }

        let text = match std::fs::read_to_string(path) {
            Ok(text) => text,
            Err(err) if err.kind() == ErrorKind::NotFound => return Ok(()),
            Err(err) => {
                return Err(err).with_context(|| format!("cannot read {}", path.display()));
            }
        };
        let parsed: CredentialsFile = serde_json::from_str(&text).with_context(|| {
            format!(
                "{} is not a valid OpenSky credentials file; it should look like \
                 {{\"clientId\": \"...\", \"clientSecret\": \"...\"}}",
                path.display()
            )
        })?;
        if parsed.client_id.is_blank() || parsed.client_secret.is_blank() {
            bail!(
                "{} has a blank clientId or clientSecret; delete the file to run on the \
                 no-key fallback sources, or re-download it from your OpenSky account",
                path.display()
            );
        }

        self.sources.opensky.client_id = Some(parsed.client_id);
        self.sources.opensky.client_secret = Some(parsed.client_secret);
        self.credentials_path = Some(path.to_path_buf());
        Ok(())
    }

    fn validate(&self) -> Result<()> {
        if self.log.filter.trim().is_empty() {
            bail!(
                "log.filter is empty; remove the key to take the default ({DEFAULT_LOG_FILTER:?})"
            );
        }
        if self.storage.db_path.as_os_str().is_empty() {
            bail!(
                "storage.db_path is empty; remove the key to take the default ({DEFAULT_DB_PATH:?})"
            );
        }
        if self.storage.retention_hours > RETENTION_HOURS_MAX {
            bail!(
                "storage.retention_hours is {} but may not exceed {RETENTION_HOURS_MAX} \
                 (7 days — privacy rule 5.1); history is configurable downward only",
                self.storage.retention_hours
            );
        }
        // Half a pair cannot authenticate, and reads as a typo rather than an intent to run
        // without credentials.
        if self.sources.opensky.client_id.is_some() != self.sources.opensky.client_secret.is_some()
        {
            bail!("sources.opensky needs both client_id and client_secret, or neither");
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::sync::atomic::{AtomicU32, Ordering};

    use super::*;

    impl EnvSource for BTreeMap<String, String> {
        fn var(&self, key: &str) -> Result<Option<String>> {
            Ok(self.get(key).cloned())
        }
    }

    /// An environment where one variable is present but unreadable — what [`SystemEnv`]
    /// reports for a value that is not valid Unicode.
    struct UnreadableEnv(&'static str);

    impl EnvSource for UnreadableEnv {
        fn var(&self, key: &str) -> Result<Option<String>> {
            if key == self.0 {
                bail!("{key} is set but is not valid Unicode")
            }
            Ok(None)
        }
    }

    /// [`Config::load_from`] with the credentials file pointed at a path that is never
    /// created.
    ///
    /// Hermetic on purpose: `Config::load` reads `credentials.json` from the working
    /// directory, and this repository's root has a real one. A test that reached it would
    /// pass or fail depending on whose machine it ran on — and would start failing the day
    /// someone checks out the repo without credentials. The tests that *want* a credentials
    /// file name one explicitly.
    fn load(path: &Path, env: &impl EnvSource) -> Result<Config> {
        load_with_credentials(path, &path.with_file_name("absent-credentials.json"), env)
    }

    fn load_with_credentials(
        path: &Path,
        credentials_path: &Path,
        env: &impl EnvSource,
    ) -> Result<Config> {
        Config::load_from(path, credentials_path, env)
    }

    fn env(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
        pairs
            .iter()
            .map(|(key, value)| ((*key).to_owned(), (*value).to_owned()))
            .collect()
    }

    fn empty_env() -> BTreeMap<String, String> {
        BTreeMap::new()
    }

    /// A self-cleaning temp directory — enough for these tests without a `tempfile`
    /// dev-dependency.
    struct TempDir {
        path: PathBuf,
    }

    impl TempDir {
        fn new(label: &str) -> Self {
            static COUNTER: AtomicU32 = AtomicU32::new(0);
            let unique = COUNTER.fetch_add(1, Ordering::Relaxed);
            let path = std::env::temp_dir().join(format!(
                "look-above-cfg-{}-{label}-{unique}",
                std::process::id()
            ));
            std::fs::create_dir_all(&path).expect("create temp dir in test");
            Self { path }
        }

        /// The path `config.toml` would occupy — deliberately not created.
        fn config_path(&self) -> PathBuf {
            self.path.join("config.toml")
        }

        /// The path `credentials.json` would occupy — deliberately not created.
        fn credentials_path(&self) -> PathBuf {
            self.path.join("credentials.json")
        }

        fn write_config(&self, contents: &str) -> PathBuf {
            let path = self.config_path();
            std::fs::write(&path, contents).expect("write config in test");
            path
        }

        fn write_credentials(&self, contents: &str) -> PathBuf {
            let path = self.credentials_path();
            std::fs::write(&path, contents).expect("write credentials in test");
            path
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.path);
        }
    }

    fn exposed(secret: Option<&SecretString>) -> Option<&str> {
        secret.map(SecretString::expose)
    }

    // --- Acceptance §M0: "missing file yields defaults, not error" -----------------------

    #[test]
    fn missing_file_yields_defaults_not_an_error() {
        let dir = TempDir::new("missing");
        let config =
            load(&dir.config_path(), &empty_env()).expect("a missing config.toml is not an error");

        assert_eq!(config, Config::default());
        assert_eq!(
            config.source_path, None,
            "nothing was read, so no source path"
        );
    }

    #[test]
    fn empty_file_is_defaults() {
        // Distinct from malformed: an empty file is valid TOML with every key absent.
        let dir = TempDir::new("empty");
        let path = dir.write_config("");
        let config = load(&path, &empty_env()).expect("an empty config.toml is valid");

        assert_eq!(
            Config {
                source_path: None,
                ..config
            },
            Config::default()
        );
    }

    // --- Acceptance §M0: "config loads from config.toml + env override" ------------------

    #[test]
    fn file_values_are_read() {
        let dir = TempDir::new("file");
        let path = dir.write_config(
            r#"
            [log]
            filter = "look_above=debug"

            [sources.opensky]
            client_id = "id-from-file"
            client_secret = "secret-from-file"

            [storage]
            db_path = "custom.db"
            retention_hours = 6
            "#,
        );
        let config = load(&path, &empty_env()).expect("valid config parses");

        assert_eq!(config.log.filter, "look_above=debug");
        assert_eq!(
            exposed(config.sources.opensky.client_id.as_ref()),
            Some("id-from-file")
        );
        assert_eq!(
            exposed(config.sources.opensky.client_secret.as_ref()),
            Some("secret-from-file")
        );
        assert_eq!(config.storage.db_path, PathBuf::from("custom.db"));
        assert_eq!(config.storage.retention_hours, 6);
        assert_eq!(config.source_path.as_deref(), Some(path.as_path()));
    }

    #[test]
    fn env_overrides_file() {
        let dir = TempDir::new("env-over-file");
        let path = dir.write_config(
            r#"
            [log]
            filter = "look_above=debug"

            [sources.opensky]
            client_id = "id-from-file"
            client_secret = "secret-from-file"

            [storage]
            db_path = "from-file.db"
            retention_hours = 6
            "#,
        );
        let config = load(
            &path,
            &env(&[
                ("LOOK_ABOVE_LOG_FILTER", "look_above=trace"),
                ("LOOK_ABOVE_OPENSKY_CLIENT_ID", "id-from-env"),
                ("LOOK_ABOVE_OPENSKY_CLIENT_SECRET", "secret-from-env"),
                ("LOOK_ABOVE_DB_PATH", "from-env.db"),
                ("LOOK_ABOVE_RETENTION_HOURS", "12"),
            ]),
        )
        .expect("valid config parses");

        assert_eq!(config.log.filter, "look_above=trace");
        assert_eq!(
            exposed(config.sources.opensky.client_id.as_ref()),
            Some("id-from-env")
        );
        assert_eq!(
            exposed(config.sources.opensky.client_secret.as_ref()),
            Some("secret-from-env")
        );
        assert_eq!(config.storage.db_path, PathBuf::from("from-env.db"));
        assert_eq!(config.storage.retention_hours, 12);
    }

    #[test]
    fn env_applies_without_a_file() {
        // Privacy rule 7.1 names environment variables as a home for credentials, so they
        // have to work with no config.toml present at all.
        let dir = TempDir::new("env-only");
        let config = load(
            &dir.config_path(),
            &env(&[
                ("LOOK_ABOVE_OPENSKY_CLIENT_ID", "id-from-env"),
                ("LOOK_ABOVE_OPENSKY_CLIENT_SECRET", "secret-from-env"),
                ("LOOK_ABOVE_RETENTION_HOURS", "1"),
            ]),
        )
        .expect("env-only configuration is valid");

        assert!(config.sources.opensky.is_configured());
        assert_eq!(config.storage.retention_hours, 1);
        assert_eq!(
            config.log.filter, DEFAULT_LOG_FILTER,
            "keys no variable touched keep their defaults"
        );
    }

    #[test]
    fn env_overrides_only_the_keys_it_names() {
        let dir = TempDir::new("partial-env");
        let path = dir.write_config("[storage]\nretention_hours = 6\ndb_path = \"kept.db\"\n");
        let config =
            load(&path, &env(&[("LOOK_ABOVE_RETENTION_HOURS", "3")])).expect("valid config parses");

        assert_eq!(config.storage.retention_hours, 3, "overridden");
        assert_eq!(
            config.storage.db_path,
            PathBuf::from("kept.db"),
            "left to the file"
        );
    }

    // --- Acceptance §M0: "repo contains config.example.toml" -----------------------------

    /// Embedded at compile time, so a build failure here means the example file went
    /// missing — acceptance §M0 requires it to exist.
    const EXAMPLE: &str = include_str!("../../../config.example.toml");

    #[test]
    fn every_env_override_is_documented_in_the_example_file() {
        // config.example.toml is the only place these names are published, so a const
        // renamed without touching the file leaves the documentation silently wrong.
        for key in [
            ENV_LOG_FILTER,
            ENV_OPENSKY_CLIENT_ID,
            ENV_OPENSKY_CLIENT_SECRET,
            ENV_DB_PATH,
            ENV_RETENTION_HOURS,
        ] {
            assert!(
                EXAMPLE.contains(key),
                "config.example.toml never mentions {key}"
            );
        }
    }

    #[test]
    fn example_file_is_equivalent_to_no_file() {
        let dir = TempDir::new("example");
        let path = dir.write_config(EXAMPLE);
        let config = load(&path, &empty_env()).expect("config.example.toml parses");

        assert_eq!(
            Config {
                source_path: None,
                ..config
            },
            Config::default(),
            "copying config.example.toml verbatim must behave exactly like having no file"
        );
    }

    // --- A present-but-broken file is NOT the missing-file case ---------------------------

    #[test]
    fn malformed_file_is_an_error_not_defaults() {
        let dir = TempDir::new("malformed");
        let path = dir.write_config("[log\nfilter = ");
        let err = load(&path, &empty_env())
            .expect_err("a present-but-broken config.toml must not silently default");

        assert!(
            err.to_string().contains("not valid configuration"),
            "unexpected: {err}"
        );
    }

    #[test]
    fn unknown_key_is_an_error() {
        // The point of deny_unknown_fields: a typo'd key must not read as "absent", which
        // is exactly how a credential goes silently missing.
        let dir = TempDir::new("unknown-key");
        let path =
            dir.write_config("[sources.opensky]\nclientid = \"typo\"\nclient_secret = \"s\"\n");
        let err = load(&path, &empty_env()).expect_err("unknown keys are rejected");

        assert!(
            err.to_string().contains("not valid configuration"),
            "unexpected: {err}"
        );
    }

    #[test]
    fn wrong_type_is_an_error() {
        let dir = TempDir::new("wrong-type");
        let path = dir.write_config("[storage]\nretention_hours = \"lots\"\n");

        load(&path, &empty_env()).expect_err("retention_hours must be an integer");
    }

    #[test]
    fn unreadable_file_is_an_error() {
        // A directory standing where config.toml should be: present, unreadable — and so
        // not the "absent" case.
        let dir = TempDir::new("unreadable");
        let path = dir.config_path();
        std::fs::create_dir_all(&path).expect("create dir in test");

        load(&path, &empty_env()).expect_err("an unreadable config.toml is not defaults");
    }

    #[test]
    fn an_unreadable_env_var_is_an_error_not_an_absent_one() {
        // The environment's own version of the broken-file case, and the reason `SystemEnv`
        // cannot use `std::env::var(..).ok()`: that flattens NotPresent and NotUnicode into
        // the same `None`. A client secret that is present but unreadable would then read as
        // "no credentials", and the app would quietly run on the fallback sources instead of
        // saying what is wrong.
        let dir = TempDir::new("unreadable-env");
        let err = load(
            &dir.config_path(),
            &UnreadableEnv(ENV_OPENSKY_CLIENT_SECRET),
        )
        .expect_err("a present-but-unreadable variable is not an unset one");

        assert!(
            err.to_string().contains(ENV_OPENSKY_CLIENT_SECRET),
            "the message must name the variable at fault: {err}"
        );
    }

    #[test]
    fn unparseable_env_override_is_an_error() {
        let dir = TempDir::new("bad-env");
        let err = load(
            &dir.config_path(),
            &env(&[("LOOK_ABOVE_RETENTION_HOURS", "soon")]),
        )
        .expect_err("a non-numeric retention override is an error");

        assert!(
            err.to_string().contains(ENV_RETENTION_HOURS),
            "the message must name the variable at fault: {err}"
        );
    }

    // --- Privacy rules -------------------------------------------------------------------

    #[test]
    fn retention_above_the_privacy_cap_is_rejected() {
        let dir = TempDir::new("retention-cap");
        let path = dir.write_config(&format!(
            "[storage]\nretention_hours = {}\n",
            RETENTION_HOURS_MAX + 1
        ));
        let err = load(&path, &empty_env()).expect_err("privacy rule 5.1 caps retention at 7 days");

        assert!(
            err.to_string().contains("privacy rule 5.1"),
            "unexpected: {err}"
        );
    }

    #[test]
    fn retention_at_the_cap_is_allowed() {
        let dir = TempDir::new("retention-max");
        let path = dir.write_config(&format!(
            "[storage]\nretention_hours = {RETENTION_HOURS_MAX}\n"
        ));
        let config = load(&path, &empty_env()).expect("the cap itself is a legal value");

        assert_eq!(config.storage.retention_hours, RETENTION_HOURS_MAX);
    }

    #[test]
    fn retention_is_configurable_downward() {
        let dir = TempDir::new("retention-down");
        let path = dir.write_config("[storage]\nretention_hours = 0\n");
        let config = load(&path, &empty_env()).expect("keeping no history is the private extreme");

        assert_eq!(config.storage.retention_hours, 0);
    }

    #[test]
    fn secrets_are_redacted_in_debug_output() {
        // Privacy rule 7.1: credentials must never reach a log, and Debug is how they would.
        let secret = SecretString::from("hunter2".to_owned());
        assert_eq!(format!("{secret:?}"), "SecretString(<redacted>)");

        let config = Config {
            sources: SourcesConfig {
                opensky: OpenSkyConfig {
                    client_id: Some(SecretString::from("id-abc".to_owned())),
                    client_secret: Some(SecretString::from("hunter2".to_owned())),
                },
            },
            ..Config::default()
        };
        let rendered = format!("{config:?}");

        assert!(
            !rendered.contains("hunter2"),
            "client secret leaked into Debug: {rendered}"
        );
        assert!(
            !rendered.contains("id-abc"),
            "client id leaked into Debug: {rendered}"
        );
    }

    // --- Credential shape ----------------------------------------------------------------

    #[test]
    fn blank_credentials_read_as_absent() {
        let dir = TempDir::new("blank-creds");
        let path =
            dir.write_config("[sources.opensky]\nclient_id = \"\"\nclient_secret = \"   \"\n");
        let config = load(&path, &empty_env()).expect("blank credentials are not an error");

        assert_eq!(config.sources.opensky.client_id, None);
        assert_eq!(config.sources.opensky.client_secret, None);
        assert!(!config.sources.opensky.is_configured());
    }

    #[test]
    fn blank_env_credential_does_not_masquerade_as_one() {
        let dir = TempDir::new("blank-env-cred");
        let config = load(
            &dir.config_path(),
            &env(&[
                ("LOOK_ABOVE_OPENSKY_CLIENT_ID", ""),
                ("LOOK_ABOVE_OPENSKY_CLIENT_SECRET", ""),
            ]),
        )
        .expect("an empty variable reads as unset, not as half a credential");

        assert!(!config.sources.opensky.is_configured());
    }

    #[test]
    fn half_a_credential_is_an_error() {
        let dir = TempDir::new("half-cred");
        let path = dir.write_config("[sources.opensky]\nclient_id = \"only-the-id\"\n");
        let err =
            load(&path, &empty_env()).expect_err("half a credential pair cannot authenticate");

        assert!(
            err.to_string().contains("both client_id and client_secret"),
            "unexpected: {err}"
        );
    }

    #[test]
    fn env_can_complete_a_credential_the_file_half_declares() {
        // The documented split: id in config.toml, secret from the environment.
        let dir = TempDir::new("split-cred");
        let path = dir.write_config("[sources.opensky]\nclient_id = \"id-from-file\"\n");
        let config = load(
            &path,
            &env(&[("LOOK_ABOVE_OPENSKY_CLIENT_SECRET", "secret-from-env")]),
        )
        .expect("file id + env secret is a complete credential");

        assert!(config.sources.opensky.is_configured());
        assert_eq!(
            exposed(config.sources.opensky.client_id.as_ref()),
            Some("id-from-file")
        );
    }

    // --- OpenSky's credentials.json --------------------------------------------------------

    /// The exact bytes `OpenSky`'s account page downloads.
    const OPENSKY_DOWNLOAD: &str =
        r#"{"clientId":"acct-api-client","clientSecret":"downloaded-secret"}"#;

    #[test]
    fn the_opensky_download_is_read_as_issued() {
        let dir = TempDir::new("creds-file");
        let credentials = dir.write_credentials(OPENSKY_DOWNLOAD);
        let config = load_with_credentials(&dir.config_path(), &credentials, &empty_env())
            .expect("OpenSky's own download format is accepted verbatim");

        assert!(config.sources.opensky.is_configured());
        assert_eq!(
            exposed(config.sources.opensky.client_id.as_ref()),
            Some("acct-api-client")
        );
        assert_eq!(
            exposed(config.sources.opensky.client_secret.as_ref()),
            Some("downloaded-secret")
        );
        assert_eq!(
            config.credentials_path.as_deref(),
            Some(credentials.as_path())
        );
    }

    #[test]
    fn an_absent_credentials_file_is_not_an_error() {
        // The no-key path: no config, no credentials file, and the app still starts — it
        // just runs on the community fallbacks.
        let dir = TempDir::new("creds-absent");
        let config = load(&dir.config_path(), &empty_env())
            .expect("a missing credentials.json is not an error");

        assert!(!config.sources.opensky.is_configured());
        assert_eq!(config.credentials_path, None);
        assert!(config.sources.opensky.credentials().is_none());
    }

    #[test]
    fn an_untouched_example_config_falls_through_to_the_credentials_file() {
        // config.example.toml ships `client_id = ""`. Those blanks must read as "absent"
        // rather than as a choice, or copying the example would shadow the download.
        let dir = TempDir::new("creds-example");
        dir.write_config(EXAMPLE);
        let credentials = dir.write_credentials(OPENSKY_DOWNLOAD);
        let config = load_with_credentials(&dir.config_path(), &credentials, &empty_env())
            .expect("blank example values do not shadow the credentials file");

        assert_eq!(
            exposed(config.sources.opensky.client_id.as_ref()),
            Some("acct-api-client")
        );
    }

    #[test]
    fn config_toml_credentials_win_over_the_credentials_file() {
        let dir = TempDir::new("creds-precedence-file");
        dir.write_config("[sources.opensky]\nclient_id = \"id-from-toml\"\nclient_secret = \"secret-from-toml\"\n");
        let credentials = dir.write_credentials(OPENSKY_DOWNLOAD);
        let config = load_with_credentials(&dir.config_path(), &credentials, &empty_env())
            .expect("valid config parses");

        assert_eq!(
            exposed(config.sources.opensky.client_id.as_ref()),
            Some("id-from-toml")
        );
        assert_eq!(
            exposed(config.sources.opensky.client_secret.as_ref()),
            Some("secret-from-toml")
        );
        assert_eq!(
            config.credentials_path, None,
            "the file was not the source, so it must not be reported as one"
        );
    }

    #[test]
    fn env_credentials_win_over_the_credentials_file() {
        let dir = TempDir::new("creds-precedence-env");
        let credentials = dir.write_credentials(OPENSKY_DOWNLOAD);
        let config = load_with_credentials(
            &dir.config_path(),
            &credentials,
            &env(&[
                ("LOOK_ABOVE_OPENSKY_CLIENT_ID", "id-from-env"),
                ("LOOK_ABOVE_OPENSKY_CLIENT_SECRET", "secret-from-env"),
            ]),
        )
        .expect("valid config parses");

        assert_eq!(
            exposed(config.sources.opensky.client_id.as_ref()),
            Some("id-from-env")
        );
    }

    /// The all-or-nothing rule: never build a pair from two different sources.
    #[test]
    fn a_half_credential_elsewhere_suppresses_the_file_entirely() {
        // config.toml names only the id. Completing it with the *file's* secret would make a
        // mismatched pair — an id from one API client, a secret from another — which fails
        // authentication with a 401 that neither file explains. So the file is ignored, and
        // the half-a-pair rule reports the real problem instead.
        let dir = TempDir::new("creds-half");
        dir.write_config("[sources.opensky]\nclient_id = \"lonely-id\"\n");
        let credentials = dir.write_credentials(OPENSKY_DOWNLOAD);
        let err = load_with_credentials(&dir.config_path(), &credentials, &empty_env())
            .expect_err("a half credential must not be completed from an unrelated pair");

        assert!(
            err.to_string().contains("both client_id and client_secret"),
            "unexpected: {err}"
        );
    }

    #[test]
    fn a_malformed_credentials_file_is_an_error_not_a_silent_fallback() {
        // Same rule as a broken config.toml: the file exists, so the operator meant to
        // authenticate. Quietly dropping to the no-key sources hides the typo.
        let dir = TempDir::new("creds-malformed");
        let credentials = dir.write_credentials("{not json");
        let err = load_with_credentials(&dir.config_path(), &credentials, &empty_env())
            .expect_err("a present-but-broken credentials.json must not silently default");

        assert!(
            err.to_string()
                .contains("not a valid OpenSky credentials file"),
            "unexpected: {err}"
        );
    }

    #[test]
    fn a_credentials_file_missing_a_field_is_an_error() {
        let dir = TempDir::new("creds-partial");
        let credentials = dir.write_credentials(r#"{"clientId":"only-the-id"}"#);

        load_with_credentials(&dir.config_path(), &credentials, &empty_env())
            .expect_err("half a downloaded credential cannot authenticate");
    }

    #[test]
    fn a_blank_credentials_file_is_an_error() {
        let dir = TempDir::new("creds-blank");
        let credentials = dir.write_credentials(r#"{"clientId":"","clientSecret":"   "}"#);
        let err = load_with_credentials(&dir.config_path(), &credentials, &empty_env())
            .expect_err("blank values in a file that exists are a mistake, not a choice");

        assert!(err.to_string().contains("blank"), "unexpected: {err}");
    }

    /// `OpenSky` adding a field to their download must not stop the app.
    #[test]
    fn unknown_fields_in_the_credentials_file_are_tolerated() {
        let dir = TempDir::new("creds-extra");
        let credentials = dir.write_credentials(
            r#"{"clientId":"acct-api-client","clientSecret":"downloaded-secret","issuedAt":"2026-07-15"}"#,
        );
        let config = load_with_credentials(&dir.config_path(), &credentials, &empty_env())
            .expect("a field we do not know about is OpenSky's business, not a failure");

        assert!(config.sources.opensky.is_configured());
    }

    #[test]
    fn credentials_from_the_file_are_redacted_in_debug_output() {
        // Privacy rule 7.1 does not care which door the secret came in through.
        let dir = TempDir::new("creds-redacted");
        let credentials = dir.write_credentials(OPENSKY_DOWNLOAD);
        let config = load_with_credentials(&dir.config_path(), &credentials, &empty_env())
            .expect("valid credentials parse");

        let rendered = format!("{config:?}");
        assert!(
            !rendered.contains("downloaded-secret"),
            "client secret leaked into Debug: {rendered}"
        );
    }

    // --- The seam into `ingest` --------------------------------------------------------------

    #[test]
    fn configured_credentials_cross_into_the_ingest_shape() {
        let dir = TempDir::new("creds-seam");
        let credentials = dir.write_credentials(OPENSKY_DOWNLOAD);
        let config = load_with_credentials(&dir.config_path(), &credentials, &empty_env())
            .expect("valid credentials parse");

        let creds = config
            .sources
            .opensky
            .credentials()
            .expect("configured credentials cross the seam");
        assert_eq!(creds.client_id.expose(), "acct-api-client");
        assert_eq!(creds.client_secret.expose(), "downloaded-secret");
    }

    // --- Filter / path sanity -------------------------------------------------------------

    #[test]
    fn empty_log_filter_is_an_error() {
        let dir = TempDir::new("empty-filter");
        let path = dir.write_config("[log]\nfilter = \"\"\n");

        load(&path, &empty_env()).expect_err("an empty filter would silence the app");
    }

    #[test]
    fn empty_db_path_is_an_error() {
        let dir = TempDir::new("empty-db-path");
        let path = dir.write_config("[storage]\ndb_path = \"\"\n");

        load(&path, &empty_env()).expect_err("an empty db_path names no file");
    }
}
